pic_url: "https://picsum.photos/seed/picsum/200/300"
date_format: "%d/%m/%Y"
string:
  length:
    max: 50
user:
  email:
    valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  password:
    length:
      min: 6
    reset:
      expried_time: 2
subject:
  length:
    min: 1
  name:
    max_length: 140
  paginate: 10
lang:
  en: "en"
  vi: "vi"
  all: ["en", "vi"]
page_size: 8
trainee_report: "trainee_report"
supervisor_report: "supervisor_report"
